### ISSUE TITLE
ImportError: No module named vectors

### ISSUE THREAD

**Issue by tokestermw** [spacy-io/sense2vec#10]
I've installed sense2vec inside a fresh virtualenv on an Ubuntu 14.04 machine python 2.7.6. 

```
pip install -e git+git://github.com/spacy-io/sense2vec.git#egg=sense2vec
```

The Cython code does not seem to be compiled.

```
(sense2vec) ~/sense2vec$ python -m sense2vec.download
/home/ubuntu/sense2vec/bin/python: No module named vectors
```

Here are the installed packages.

```
(sense2vec) ~/sense2vec$ pip freeze
argparse==1.2.1
cloudpickle==0.2.1
cymem==1.30
murmurhash==0.26.1
numpy==1.10.4
plac==0.9.1
preshed==0.46.2
semver==2.4.1
-e git://github.com/spacy-io/sense2vec.git@e27522f838739f033c048064dfc3077f7a4e956f#egg=sense2vec-master
six==1.10.0
spacy==0.100.6
sputnik==0.9.3
thinc==5.0.6
ujson==1.35
wsgiref==0.1.2
```

Same error without virtualenv.

thx

**Comment by henningpeters** [comment]
You likely got an error from pip you might have overlooked. Maybe you don't have cython installed?

**Comment by tokestermw** [comment]
Installing Cython after sense2vec gave the same error as above.

Installing Cython first then install sense2vec I get an error:

```
  ...
  File "/home/ubuntu/sense2vec/src/sense2vec/bin/cythonize.py", line 195, in main

    find_process_files(root_dir)

  File "/home/ubuntu/sense2vec/src/sense2vec/bin/cythonize.py", line 187, in find_process_files

    process(cur_dir, fromfile, tofile, function, hash_db)

  File "/home/ubuntu/sense2vec/src/sense2vec/bin/cythonize.py", line 161, in process

    processor_function(fromfile, tofile)

  File "/home/ubuntu/sense2vec/src/sense2vec/bin/cythonize.py", line 72, in process_pyx

    raise Exception('Cython failed')

Exception: Cython failed

Cythonizing sources

/home/ubuntu/sense2vec/bin/python

/home/ubuntu/sense2vec/src/sense2vec/bin/cythonize.py

sense2vec

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ubuntu/sense2vec/src/sense2vec/setup.py", line 176, in <module>

    setup_package()

  File "/home/ubuntu/sense2vec/src/sense2vec/setup.py", line 131, in setup_package

    generate_cython(root, 'sense2vec')

  File "/home/ubuntu/sense2vec/src/sense2vec/setup.py", line 70, in generate_cython

    raise RuntimeError('Running cythonize failed')

RuntimeError: Running cythonize failed

----------------------------------------
Cleaning up...
  Removing temporary dir /home/ubuntu/sense2vec/build...
Command python setup.py egg_info failed with error code 1 in /home/ubuntu/sense2vec/src/sense2vec
Exception information:
Traceback (most recent call last):
  File "/home/ubuntu/sense2vec/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/ubuntu/sense2vec/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/ubuntu/sense2vec/local/lib/python2.7/site-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/home/ubuntu/sense2vec/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/ubuntu/sense2vec/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/ubuntu/sense2vec/src/sense2vec
```

But! After installing Cython then spacy then sense2vec. I was able to install and do `python -m sense2vec.download`.

**Comment by henningpeters** [comment]
Sorry for the rocky experience. sense2vec is in alpha stage and before its first release. Any help to smoothen out those issues is greatly appreciated.

I think this here is not a bug though. The advise to install the repo via pip is just wrong/incomplete as it assumes you have already cython installed - which won't be a requirement for a release anymore, hence the setup.py doesn't contain cython as dependency.
