### ISSUE TITLE
Error while using most_similar

### ISSUE THREAD

**Issue by tarunw07** [spacy-io/sense2vec#17]
s2v.most_similar(query_vector, 3)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sense2vec/vectors.pyx", line 154, in sense2vec.vectors.VectorMap.most_similar (sense2vec/vectors.cpp:4847)
  File "spacy/strings.pyx", line 104, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2339)
IndexError: 2065123256

**Comment by tarunw07** [comment]
Can anyone help me?

**Comment by honnibal** [comment]
Try now? Just pushed a new version.

I'm not sure what I did wrong with the BLAS library wrapper, `cython-blis`. For now I've just written the `dotv` function in Cython. This version is probably a fair bit slower than the BLAS one, but at least it should work for now.

I've also pushed 0.6.0 to PyPi.

**Comment by elyase** [comment]
wow, sense2vec on pypi, didn't expect that one. Thanks a lot for you work Matthew!

**Comment by tarunw07** [comment]
Yes it worked now. Thanks a alot Matthew.
